cloudoperators/heureka

.github/dependabot.yml
Use correct package ecosystem value for go (gomod)
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
=> chore(dependabot): set package-ecosystem gomod

README.md
Added 'Value Proposition', and 'Architecture & Design' contents
=> chore(doc): readme product design content updates

internal/api/graphql/graph/generated.go, internal/api/graphql/graph/queryCollection/issueMatch/addEvidence.graphql, internal/api/graphql/graph/queryCollection/issueMatch/removeEvidence.graphql, internal/api/graphql/graph/resolver/mutation.go, internal/api/graphql/graph/schema/mutation.graphqls, internal/app/interface.go, internal/app/issue_match.go, internal/app/issue_match_test.go, internal/database/interface.go, internal/database/mariadb/issue_match.go, internal/database/mariadb/issue_match_test.go, internal/e2e/issue_match_query_test.go, internal/mocks/mock_Database.go, internal/mocks/mock_Heureka.go
Add the following mutations:
```
addEvidenceToIssueMatch(issueMatchId: ID!, evidenceId: ID!): IssueMatch!
removeEvidenceFromIssueMatch(issueMatchId: ID!, evidenceId: ID!): IssueMatch!
```
=> feat(issueMatch): add add/remove evidence mutation

internal/api/graphql/graph/generated.go, internal/api/graphql/graph/queryCollection/activity/addIssue.graphql, internal/api/graphql/graph/queryCollection/activity/removeIssue.graphql, internal/api/graphql/graph/queryCollection/issue/addComponentVersion.graphql, internal/api/graphql/graph/queryCollection/issue/removeComponentVersion.graphql, internal/api/graphql/graph/resolver/mutation.go, internal/api/graphql/graph/schema/mutation.graphqls, internal/app/activity.go, internal/app/activity_test.go, internal/app/interface.go, internal/app/issue.go, internal/app/issue_test.go, internal/database/interface.go, internal/database/mariadb/activity.go, internal/database/mariadb/activity_test.go, internal/database/mariadb/issue.go, internal/database/mariadb/issue_test.go, internal/e2e/activity_query_test.go, internal/e2e/issue_query_test.go, internal/mocks/mock_Database.go, internal/mocks/mock_Heureka.go
Add following mutations:
```
addComponentVersionToIssue(issueId: ID!, componentVersionId: ID!): Issue!
removeComponentVersionFromIssue(issueId: ID!, componentVersionId: ID!): Issue!
addIssueToActivity(activityId: ID!, issueId: ID!): Activity!
removeIssueFromActivity(activityId: ID!, issueId: ID!): Activity!
```
=> feat(issue): add mutations for activities/componentVersions

.github/workflows/build_images.yaml, Dockerfile.scanner-k8s-assets, Dockerfile.scanner-keppel, Dockerfile.scanner-nvd, Makefile, go.mod, scanner/k8s-assets/go.mod, scanner/k8s-assets/main.go, scanner/keppel/go.mod, scanner/keppel/main.go, scanner/nvd/go.mod, scanner/nvd/main.go
Its not verified if the github action does work, we need to merge to verify working
=> build(images) : building and publishing of images

.github/workflows/helm-release.yaml, scanner/k8s-assets/chart/k8s-assets-scanner/values.yaml, scanner/keppel/chart/keppel-scanner/.helmignore, scanner/keppel/chart/keppel-scanner/Chart.yaml, scanner/keppel/chart/keppel-scanner/README.md, scanner/keppel/chart/keppel-scanner/templates/NOTES.txt, scanner/keppel/chart/keppel-scanner/templates/_helpers.tpl, scanner/keppel/chart/keppel-scanner/templates/config/_scanner_config.yaml.tpl, scanner/keppel/chart/keppel-scanner/templates/configmap.yaml, scanner/keppel/chart/keppel-scanner/templates/cronjob.yaml, scanner/keppel/chart/keppel-scanner/templates/secrets.yaml, scanner/keppel/chart/keppel-scanner/templates/serviceaccount.yaml, scanner/keppel/chart/keppel-scanner/values.yaml, scanner/nvd/chart/nvd-scanner/.helmignore, scanner/nvd/chart/nvd-scanner/Chart.yaml, scanner/nvd/chart/nvd-scanner/README.md, scanner/nvd/chart/nvd-scanner/templates/NOTES.txt, scanner/nvd/chart/nvd-scanner/templates/_helpers.tpl, scanner/nvd/chart/nvd-scanner/templates/config/_scanner_config.yaml.tpl, scanner/nvd/chart/nvd-scanner/templates/configmap.yaml, scanner/nvd/chart/nvd-scanner/templates/cronjob.yaml, scanner/nvd/chart/nvd-scanner/templates/secrets.yaml, scanner/nvd/chart/nvd-scanner/templates/serviceaccount.yaml, scanner/nvd/chart/nvd-scanner/values.yaml
- Added keppel helm chart
- Added nvd helm chart
- Updated the heureka url in the values.yaml
- Added the scanners helm build and publish
=> Feat: Add scanners helm charts

internal/api/graphql/graph/baseResolver/service.go, internal/api/graphql/graph/generated.go, internal/api/graphql/graph/model/models.go, internal/api/graphql/graph/model/models_gen.go, internal/api/graphql/graph/queryCollection/service/withMetadata.graphql, internal/api/graphql/graph/schema/service.graphqls, internal/app/service/service_handler.go, internal/app/service/service_handler_test.go, internal/database/interface.go, internal/database/mariadb/entity.go, internal/database/mariadb/service.go, internal/database/mariadb/service_test.go, internal/e2e/service_query_test.go, internal/entity/common.go, internal/entity/service.go, internal/entity/test/service.go, internal/mocks/mock_Database.go
This PR adds the following two aggregations for services:
- Count of ComponentInstances
- Count of IssueMatches
- Closes #249 
Tests:
- E2E testing metadata (aggregation)
- App testing ListServices with aggregation
- DB testing individual aggregation functions
=> feat(services): add aggregations

scanner/k8s-assets/processor/processor.go, scanner/keppel/main.go, scanner/keppel/processor/processor.go, scanner/keppel/scanner/scanner.go
Keppel does not scan in all cases the top layer of an image. The primary cause of that is multi-arch images. In such cases we need to list all manifests of the manifest and check for vulnerabilities on those.
In perspective, we need to decide if that is as well stored in different versions that are related to each other instead.
#247 
- [] 🙅 no, because they aren't needed
=> fix: fetch sub-manifests from keppel

internal/api/graphql/graph/model/models.go, internal/api/graphql/graph/queryCollection/issue/withMetadata.graphql, internal/database/mariadb/entity.go, internal/database/mariadb/issue.go, internal/database/mariadb/issue_test.go, internal/database/mariadb/service.go, internal/e2e/issue_query_test.go, internal/entity/issue.go, internal/entity/test/issue.go
This PR refactors the aggreation query for Issues by utilizing [CTE](https://mariadb.com/kb/en/with/) feature in MariaDB. Additionally, the `componentInstanceCount` is now showing the correct value.
- Closes Issue #278
=> feat(issue): refactor issue aggregations

internal/app/issue_match/issue_match_handler_test.go
For some reason, it is not guaranteed when having two db.On("someMethod") calls for the same method, which has different Match logics that both are correctly called when multiple calls do occur after each other. Therefore, this test failed 1/5 of calls.
I, therefore, changed the logic slightly to make the test reliably work.
#319 
=> fix(issue_match_handler_test): fixed flaky test

.github/workflows/codeql.yaml
The `setup` and `codeql` jobs run independently, so the `mockery` command is not found in the `codeql` job. Therefore, install it through the custom `build_query`
=> chore: update build_query in codeql.yaml

.github/workflows/tests.yaml, internal/database/interface.go
This PR adds `go:generate` directive to generate the mockery via `go generate`
=> chore: add mockery generate directive

go.mod, internal/api/graphql/graph/baseResolver/component_instance.go, internal/database/mariadb/component_instance.go, internal/database/mariadb/component_instance_test.go, internal/entity/component_instance.go
Added wild card search for component instances
- Fixes #232
added DB test to component_instance_test.go
=> feat(comp.backend): Implement Wild Card Search for Component Instance

internal/api/graphql/graph/baseResolver/issue_variant.go, internal/database/mariadb/issue_variant_test.go
Add the `secondaryName` to the filter building in the `IssueVariant` BaseResolver, so that filtering via API is possible.
- Closes #373
=> feat(issueVariant): add filter by secondaryName in baseResolver

go.mod, internal/app/activity/activity_handler.go, internal/app/component/component_handler.go, internal/app/component_instance/component_instance_handler.go, internal/app/component_version/component_version_handler.go, internal/app/evidence/evidence_handler.go, internal/app/issue/issue_handler.go, internal/app/issue_match/issue_match_handler.go, internal/app/issue_match_change/issue_match_change_handler.go, internal/app/issue_repository/issue_repository_handler.go, internal/app/issue_variant/issue_variant_handler.go, internal/app/service/service_handler.go, internal/app/support_group/support_group_handler.go, internal/app/user/user_handler.go, internal/database/mariadb/activity.go, internal/database/mariadb/component.go, internal/database/mariadb/component_instance.go, internal/database/mariadb/component_version.go, internal/database/mariadb/evidence.go, internal/database/mariadb/issue.go, internal/database/mariadb/issue_match.go, internal/database/mariadb/issue_match_change.go, internal/database/mariadb/issue_repository.go, internal/database/mariadb/issue_variant.go, internal/database/mariadb/service.go, internal/database/mariadb/support_group.go, internal/database/mariadb/user.go, internal/e2e/metadata_test.go
Add assignments in app handlers
Add inserts in database querries
Adjust tests
issue-360 - add updated_by change for insert of element
=> feat(authN) - Add updated_by to inserts #360

scanner/keppel/chart/keppel-scanner/templates/cronjob.yaml, scanner/keppel/chart/keppel-scanner/values.yaml, scanner/keppel/scanner/config.go, scanner/keppel/scanner/scanner.go
Separated User Domain from Keppel Domain, to allow authentication with a user that is living in a different domain then keppel itself.
#391
=> ci(keppel): seperate user and keppel domain

Makefile, scanner/k8s-assets/Dockerfile, scanner/keppel/Dockerfile, scanner/nvd/Dockerfile
-------
This PR adds linkerd to the Docker images of the scanners. This would then allow TLS to be used for connectivity between pods.
- Related Issue #391
=> feat(deployment): Change Docker files to use linkerd

internal/database/mariadb/component_instance.go
Fix redundant filter line in coponentInstance
=> Fix(componentInstance): Remove redundant filter line

internal/api/graphql/graph/baseResolver/issue_match.go, internal/api/graphql/graph/schema/issue_match.graphqls, internal/database/mariadb/issue_match.go, internal/database/mariadb/issue_match_test.go, internal/database/mariadb/test/fixture.go, internal/entity/issue_match.go
Add the possibility to filter `IssueMatch` by ServiceOwner:
- ServiceOwnerUsername
- ServiceOwnerUniqueUserId
- Closes #558
=> feat(issueMatch): add serviceOwner filter

internal/app/issue_match/issue_match_handler_events.go
Fixing missing user reference on the creation of IssueMatches in the OnComponentInstaceAttachedToComponentVersion event. This results in no Issue Matches being created when a k8s scanner is running after the Keppel scanner.
The user is for now static and this needs to be adjusted post MVP
=> fix: missing user reference

internal/api/graphql/graph/baseResolver/component_version.go, internal/database/mariadb/cursor.go
When ComponentVersions are ordered by severity, we additionally pass the ComponentVersionId for ordering.
=> fix(cv): add id when severity order is set

scanner/k8s-assets/processor/processor.go, scanner/k8s-assets/processor/processor_test.go, scanner/k8s-assets/scanner/scanner.go
Groups Jobs below a PodSet and changed naming from PodReplicaSet to  to PodSet to make clear that this includes all kinds of pod sets such as ReplicaSet, StatefullSet, DaemonSet, Job etc.
=> fix: grouping cronjobs

internal/api/graphql/graph/baseResolver/issue.go, internal/api/graphql/graph/queryCollection/issueCounts/query.graphql, internal/api/graphql/graph/resolver/query.go, internal/api/graphql/graph/schema/issue.graphqls, internal/api/graphql/graph/schema/query.graphqls, internal/database/mariadb/issue.go, internal/database/mariadb/issue_test.go, internal/e2e/issue_counts_query_test.go, internal/entity/issue.go
Add `isseCounts` query and add `SupportGroupCcrn` to `IssueFilter`. This enables filtering `issueCounts` by severity for a Support Group (i.e. for all services that belong to a Support Group).
- Closes #592
=> feat(issueCounts): allow filter by support group

internal/api/graphql/graph/baseResolver/issue.go, internal/api/graphql/graph/baseResolver/service.go, internal/api/graphql/graph/schema/issue.graphqls, internal/api/graphql/graph/schema/service.graphqls, internal/database/mariadb/issue.go, internal/entity/issue.go
Add `issueCounts` to the `ServiceConnection` that allows to fetch issueCounts for all Services.
Example query:
```graphql
{
Services{
issueCounts{
critical
high
medium
low
none
}
edges{
node{
ccrn
}
}
}
}
```
- Closes #600
=> feat(issueCounts): allow easy filter by all services

scanner/k8s-assets/processor/processor.go
The k8s-assets scanner is reading owner
information from the owner-helm-chart.
The supportGroup attribute is mandatory, but
the service attribute is optional.
Currently, if the scanner encounters such a case,
it adds the componentInstance to a None service.
This will lead to one none service, that has
componentInstances assigned from multiple
supportGroup including all their vulnerabilities.
Instead of a single 'none` service for all Support Groups, we want to have one per Support Group.
The name for this will be "Unknown-{SupportGroupName}"
> Remove if not …
=> feat(service): Assign supportgroup to unknown service

scanner/k8s-assets/main.go
Add `cluster` name to the `k8s-scanner` tag to identify the scanner run.
- Fixes #685
=> fix(k8s-scanner): add cluster to tag name

internal/api/graphql/graph/baseResolver/issue_match.go, internal/api/graphql/graph/schema/issue_match.graphqls
The CSC scanner requires the ability to search issue matches by issue id + component instance id so that it can check for existing issue matches before directly creating a new one for non-compliant findings. Because many resources scanned by the CSC scanner do not have components / component versions, using the existing componentCcrn field in the filter would not work. 
Since filtering by componentInstanceId was already implemented at the app/db layer, this change just adds ComponentInstanceId as a field to the IssueMatchFilter in the GraphQL schema and adds logic to ensure it gets set properly in the filter object that gets passed down to the db layer. 
Closes Issue #825 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also …
=> feat(issueMatch): Added ComponentInstanceId to IssueMatchFilter in GraphQL API

internal/database/mariadb/autoclose.go
The AutoClosing SQL statement wasn't considering the case where only one Scan is present. In that case, all IssueMatches haven been wrongly updated to mitigated.
- Closes #823
=> fix(autoclosing): only update if there was a previous scan
