- Makefile
- docker-compose.yaml
Remove obsolete version section from docker-compose
Add build command to buildx, to be compatible with linux native systems
> fix: makefile and docker-compose fix issues

- internal/app/heureka.go
> fix: actually running event register to not exceed buffer

- charts/heureka/templates/ingress.yaml
> fix: fixed ingress helm chart template

- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/task.md
This PR creates 2 issue templates for Heureka epics and tasks.
> feat(issue_templates):Create Heureka epic/task issue templates

- README.md
Simplified the description section as agreed in the Slack convo.
- Related Issue #255
> doc(readme): Simplified heureka description

- scanner/nvd/main.go
- scanner/nvd/processor/processor.go
Time window fetching was not working as intended
#247 
- [] I have commented my code, particularly in hard-to-understand areas
> fix(nvd):  time window fetching

- internal/api/graphql/graph/model/models.go
- internal/api/graphql/graph/resolver/query.go
- internal/database/mariadb/component.go
- internal/database/mariadb/component_instance.go
- internal/database/mariadb/issue.go
- internal/database/mariadb/service.go
- internal/database/mariadb/support_group.go
- internal/database/mariadb/user.go
Add alphabetical order for following filterValues:
- Service names
- SupportGroup names
- Component names
- ComponentInstance CCRN
- User name
- User Unique ID
Custom Order:
- IssueType
- Severity
- IssueMatchStatus
Closes #301
> feat(filter): add ordering for filter values

- internal/database/mariadb/test/fixture.go
We have a lot of flaky tests, this
n/a
> refactor(fixture): add some randomness to unique names

- .github/licenserc.yaml
> chore: increase license location threshold

- charts/heureka/templates/PodMonitor.yaml
- charts/heureka/templates/deployment.yaml
> Fix: Resolve the double port expose for Prometheus metrics

- .github/workflows/codeql.yaml
Error:
```
error: reusable workflows should be referenced at the top-level `jobs.*.uses' key, not within steps
```
Create a setup job to fix the error.
> chore: create setup job in codeql.yaml

- docs/product_design_documentation.md
Updated the document using concise terms; also added personas, high-level features, and high-level architecture diagram.
- Related Issue #255
> chore(doc): Updated Product Design Document

- README.md
Updated the **Architecture and design** section of the readme to reference Heureka's High-level features and architecture diagram.
- Related Issue #255 
> chore(doc): updated readme post pdd update

- Dockerfile
- internal/api/graphql/graph/resolver/resolver.go
At the top of our resolver.go, between package and import, add the following line:
```
//go:generate go run github.com/99designs/gqlgen generate
```
This magic comment tells go generate what command to run when we want to regenerate our code. To run go generate recursively over your entire project, use this command:
```
go generate ./...
```
So we can use this step in the Dockerfile to generate the code.
https://github.com/99designs/gqlgen/blob/master/docs/content/getting-started.md
> chore: add generation step

- Dockerfile
- internal/api/graphql/graph/resolver/resolver.go
- internal/database/interface.go
Generating the code via `go generate` caused issues with resolving some imports. Therefore, the code generation has been moved into the Dockerfile.
> chore: remove go:generate and add code gen to dockerfile

- internal/api/graphql/graph/baseResolver/component_instance.go
- internal/database/mariadb/component_instance.go
- internal/database/mariadb/component_instance_test.go
- internal/entity/component_instance.go
Allow `ComponentInstances` to be filtered by `ServiceCcrn`.
- Closes #342
> feat(ci): add service ccrn filter

- internal/api/graphql/graph/baseResolver/component_instance.go
- internal/database/mariadb/component_instance.go
- internal/database/mariadb/component_instance_test.go
Implement CCRN filter for Component Instances
- Closes #351
> feat(componentInstance): filter by ccrn

- scanner/k8s-assets/chart/k8s-assets-scanner/templates/rbac.yaml
Adds RBAC to the k8s service Account required to scan k8s assets
Relates to #206 
> ci(k8s): added rbac to k8s serviceAccount

- internal/app/issue/issue_handler_events.go
> fix:  added missing updated_by

- scanner/nvd/processor/processor.go
NVD scanner was unable to create IssueVariants because the field validation was throwing an error when the Golang Nulltype was set
- [] I have commented my code, particularly in hard-to-understand areas
> fix(nvd): set default value to avoid validation errors on API

- Makefile
> fix(Makefile): Fix duplicated test targets in makefile

- .github/CODEOWNERS
> Privilege escalation

- docs/adr/user.md
Add systemuser information
Add scanner auth info in user context
Add UI user auth info in user context
> task(authN) Update documentation regarding systemuser

- Dockerfile
- Makefile
> chore(dependencies): Change mockery version

- internal/app/common/pagination_helpers.go
After cursors showed the same value, because the list contained the reference to the same variable.
> fix(cursor): remove shared reference

- internal/api/graphql/gqlgen.yml
- internal/api/graphql/graph/baseResolver/issue_match.go
- internal/api/graphql/graph/queryCollection/service/directRelations.graphql
- internal/api/graphql/graph/resolver/service.go
- internal/api/graphql/graph/schema/service.graphqls
- internal/database/mariadb/issue_match.go
- internal/database/mariadb/issue_match_test.go
- internal/e2e/service_query_test.go
- internal/entity/issue_match.go
Add `IssueMatches` to `Service` type on the API.
- Closes #514 
> feat(api): add isueMatches to services

- internal/api/graphql/gqlgen.yml
- internal/api/graphql/graph/baseResolver/issue.go
- internal/api/graphql/graph/model/models.go
- internal/api/graphql/graph/queryCollection/componentVersion/withIssueCounts.graphql
- internal/api/graphql/graph/resolver/component_version.go
- internal/api/graphql/graph/schema/common.graphqls
- internal/api/graphql/graph/schema/component_version.graphqls
- internal/api/graphql/graph/schema/issue.graphqls
- internal/app/issue/issue_handler.go
- internal/app/issue/issue_handler_events.go
- internal/app/issue/issue_handler_interface.go
- internal/database/interface.go
- internal/database/mariadb/entity.go
- internal/database/mariadb/issue.go
- internal/database/mariadb/issue_test.go
- internal/database/mariadb/test/fixture.go
- internal/e2e/component_version_query_test.go
- internal/entity/issue.go
- internal/entity/severity.go
Adds issue counts by severity for component versions.
- Closes #506
> feat(componentVersion): add issueCounts

- internal/api/graphql/graph/baseResolver/component_version.go
- internal/api/graphql/graph/schema/component_version.graphqls
- internal/database/mariadb/component_version.go
- internal/database/mariadb/component_version_test.go
- internal/entity/component_version.go
Allow filter by service (id, ccrn) for ComponentVersion.
- Closes #528 
-
> feat(componentVersion): filter by service

- scanner/k8s-assets/processor/processor.go
Set default registry.
- [x ] 🐛 Bug Fix
- Closes #533 
- [x ] 🙅 no documentation needed
> fix(k8s-scanner): set default registry

- internal/api/graphql/graph/baseResolver/component_version.go
- internal/api/graphql/graph/queryCollection/componentVersion/withOrder.graphql
- internal/api/graphql/graph/resolver/component.go
- internal/api/graphql/graph/resolver/issue.go
- internal/api/graphql/graph/resolver/query.go
- internal/api/graphql/graph/schema/component.graphqls
- internal/api/graphql/graph/schema/component_version.graphqls
- internal/api/graphql/graph/schema/issue.graphqls
- internal/api/graphql/graph/schema/query.graphqls
- internal/app/component_version/component_version_handler.go
- internal/app/component_version/component_version_handler_test.go
- internal/database/interface.go
- internal/database/mariadb/component_version.go
- internal/database/mariadb/component_version_test.go
- internal/database/mariadb/cursor.go
- internal/database/mariadb/entity.go
- internal/database/mariadb/issue_match_test.go
- internal/database/mariadb/order.go
- internal/database/mariadb/service.go
- internal/database/mariadb/test/common.go
- internal/database/mariadb/testdata/component_version_order/component_version_issue.json
- internal/database/mariadb/testdata/component_version_order/issue_variant.json
- internal/database/mariadb/testdata/component_version_order/readme.md
- internal/e2e/component_version_query_test.go
- internal/entity/common.go
- internal/entity/component_version.go
- internal/entity/order.go
- internal/entity/test/component_version.go
Add order by `Severity` for `ComponentVersion`.
- Closes #526
> feat(componentVersion): order by severity

- internal/e2e/component_version_query_test.go
Add additional check to avoid counting duplicates in test data setup.
> fix(test): fix flaky issueCount test for ComponentVersions

- internal/database/mariadb/service.go
Filter parameter was added at wrong position
> fix(service): add support group ccrn filter at right position

- internal/api/graphql/graph/resolver/issue.go
- internal/api/graphql/graph/schema/issue.graphqls
added orderBy to issueMatchResolver from Issue to allow fetching of earliest TRD and highest severity Issue Match
> feat: added orderBy to issueMatchResolver from Issue

- internal/app/common/pagination_helpers.go
- internal/app/component_version/component_version_handler_test.go
- internal/database/mariadb/component_version.go
- internal/database/mariadb/component_version_test.go
- internal/database/mariadb/cursor.go
- internal/database/mariadb/entity.go
Consider issue counts for issue and add id if they're present. Additionally, fix variable reference error in Pagination helper, which led to wrong cursors.
> fix(componentVersion): fix cursor fields

- scanner/k8s-assets/processor/processor.go
Fixed lookup of k8s component versions
> fix: k8s version lookup

- internal/api/graphql/graph/model/models.go
- internal/api/graphql/graph/schema/common.graphqls
- internal/entity/common.go
Add link to external CVSS calculator for displaying the CVSS vector.
- Closes #581
> feat(cvss): add external url to calculator

- internal/api/graphql/graph/model/models.go
- internal/api/graphql/graph/queryCollection/issueVariant/create.graphql
- internal/api/graphql/graph/queryCollection/issueVariant/createWithRating.graphql
- internal/api/graphql/graph/queryCollection/issueVariant/directRelations.graphql
- internal/api/graphql/graph/queryCollection/issueVariant/update.graphql
- internal/api/graphql/graph/schema/issue_variant.graphqls
- internal/database/mariadb/entity.go
- internal/database/mariadb/init/schema.sql
- internal/database/mariadb/issue_variant.go
- internal/database/mariadb/issue_variant_test.go
- internal/database/mariadb/test/fixture.go
- internal/e2e/issue_variant_query_test.go
- internal/entity/issue_variant.go
- scanner/nvd/Makefile
- scanner/nvd/client/generated.go
- scanner/nvd/models/models.go
- scanner/nvd/processor/config.go
- scanner/nvd/processor/processor.go
Add external url attribute to IssueVariant that points to detailed information for the found Issue(Variant).
- Closes #580
> feat(issueVariant): add external url to issue variant

- internal/api/graphql/graph/baseResolver/common.go
- internal/api/graphql/graph/resolver/component_filter.go
- internal/api/graphql/graph/resolver/component_instance_filter.go
Add missing update of variables for issue-487
> Fix var names

- internal/api/graphql/graph/baseResolver/component_instance.go
- internal/api/graphql/graph/schema/component_instance.graphqls
- internal/database/mariadb/component_instance.go
- internal/database/mariadb/component_instance_test.go
- internal/entity/component_instance.go
Allow filtering ComponentInstances by ComponentVersion version.
- Closes #584
> feat(componentInstance): add filter by componentVersion version

- internal/api/graphql/graph/model/models.go
- scanner/k8s-assets/processor/processor.go
K8S scanner sets the attributes:
- Pod
- Container
- Closes #588
> feat(k8s-scanner): set pod and container

- internal/api/graphql/gqlgen.yml
- internal/api/graphql/graph/baseResolver/issue.go
- internal/api/graphql/graph/queryCollection/service/withIssueCounts.graphql
- internal/api/graphql/graph/resolver/service.go
- internal/api/graphql/graph/schema/service.graphqls
- internal/database/mariadb/issue.go
- internal/database/mariadb/issue_test.go
- internal/e2e/service_query_test.go
- internal/entity/issue.go
Add `issueCounts` by severity to Service:
```graphql
{
Services {
edges {
node {
issueCounts {
critical
high
medium
low
none
}
}
}
}
```
- Closes #591
> feat(service): add issueCounts

- internal/api/graphql/graph/baseResolver/issue.go
- internal/api/graphql/graph/model/models.go
- internal/api/graphql/graph/queryCollection/issue/withOrder.graphql
- internal/api/graphql/graph/resolver/activity.go
- internal/api/graphql/graph/resolver/component_version.go
- internal/api/graphql/graph/resolver/query.go
- internal/api/graphql/graph/schema/activity.graphqls
- internal/api/graphql/graph/schema/component_version.graphqls
- internal/api/graphql/graph/schema/issue.graphqls
- internal/api/graphql/graph/schema/query.graphqls
- internal/app/issue/issue_handler.go
- internal/app/issue/issue_handler_test.go
- internal/database/interface.go
- internal/database/mariadb/cursor.go
- internal/database/mariadb/entity.go
- internal/database/mariadb/issue.go
- internal/database/mariadb/issue_test.go
- internal/database/mariadb/order.go
- internal/e2e/common/issue.go
- internal/e2e/issue_query_test.go
- internal/entity/common.go
- internal/entity/issue.go
- internal/entity/order.go
- internal/entity/test/issue.go
Expose ordering without backend function to API, so frontend can proceed with implementation.
> feat(issue): add ordering

- internal/api/graphql/graph/schema/service.graphqls
Expose order possibility by severity for service.
> feat(service): expose severity order to api

- internal/database/mariadb/issue.go
Use `HAVING` in SQL statement to filter aggregation.
> fix(issue): use having for cursor

- internal/api/graphql/graph/baseResolver/service.go
- internal/app/service/service_handler_test.go
- internal/database/mariadb/cursor.go
- internal/database/mariadb/service.go
- internal/database/mariadb/service_test.go
- internal/database/mariadb/testdata/service_order/component_instance.json
- internal/database/mariadb/testdata/service_order/component_version_issue.json
- internal/database/mariadb/testdata/service_order/readme.md
- internal/e2e/service_query_test.go
Order Services by severity count.
- Closes #579
> feat(service): add order by severity

- internal/api/graphql/graph/baseResolver/user.go
- internal/e2e/oidc_auth_test.go
- internal/e2e/token_auth_test.go
> Fix: remove redundant check from e2e tests

- scanner/k8s-assets/processor/processor.go
Use correct template string syntax.
> fix(k8s-scanner): update template string

- scanner/k8s-assets/processor/processor.go
Add placeholder 'Unknown' when SupportGroup is empty
> fix(service): unknown service

- .vscode/extensions.json
Add a file with suggested extensions for VSCode users.
After our discussion this morning and the insight that even people in the core team didn't know about the ginkgo plugin for VSCode, this PR fixes this issues and allows easy onboarding for new developers and dissemination of team knowledge. 
Closes #666
> Add .vscode/extensions.json for recommended extensions

- internal/api/graphql/graph/baseResolver/scannerrun.go
This fixes  the internal server error which was reported.
- Closes #684
> Fix: Internal server error nil pointer

- .github/licenserc.yaml
> fix(actions): set current year in new license headers

- internal/database/mariadb/database.go
Performance fix
- [x ] 🙅 no documentation needed
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
> Speed up unit database tests by moving Sleep call to appropriate position and reduce sleep time tenfold

- scanner/keppel/main.go
Check whether VulnerabilityStatus is valid.
> fix(keppel-scanner): check for valid vulnerability status

- internal/api/graphql/graph/resolver/mutation.go
- internal/app/component_instance/component_instance_handler.go
- internal/app/component_instance/component_instance_handler_interface.go
- internal/app/component_instance/component_instance_handler_test.go
- internal/database/mariadb/test/fixture.go
- internal/e2e/component_instance_query_test.go
- scanner/k8s-assets/processor/processor.go
- Set UUID in k8s-scanner
- Create ScannerRunComponentInstance relation in UpdateComponentInstance
> fix(autoclosing): set uuid in k8s-scanner

- internal/api/graphql/graph/baseResolver/component_version.go
- internal/api/graphql/graph/model/models.go
- internal/api/graphql/graph/schema/component_version.graphqls
- internal/database/mariadb/component_version_test.go
- internal/database/mariadb/cursor.go
- internal/database/mariadb/order.go
- internal/entity/order.go
Add order by `repository` for ComponentVersion.
- Closes #671
> feat(componentVersion): add order by repository

- .github/workflows/release.yaml
- .releaserc.json
Setupt Semantic Release.
- Closes #638
> chore: setup semantic-release

- docs/releases.md
This PR adds documentation for releases in Heureka.
> docs: add releases.md

- internal/database/mariadb/cursor.go
Cursor for Issues contained the wrong value for the PrimarName attribute.
> fix(issue): set primary name in cursor

- internal/api/graphql/graph/baseResolver/issue.go
- internal/api/graphql/graph/baseResolver/vulnerability.go
- internal/api/graphql/graph/queryCollection/vulnerability/query.graphql
- internal/api/graphql/graph/schema/vulnerability.graphqls
- internal/database/mariadb/issue.go
- internal/database/mariadb/issue_test.go
- internal/e2e/vulnerability_query_test.go
- internal/entity/issue.go
Add counts by severity to the Vulnerability query.
- Closes #772
> feat(vulnerability): add counts by severity

- .github/workflows/check-migration-files.yaml
- Makefile
- Check migration files to fail for Pull Requests modifying existing migration files.
- Change target for CallCached check to be more descriptive
> Add check migration files

- internal/database/mariadb/test/fixture.go
Add more randomness to IssueVariant name to avoid having duplicates.
- Closes #635
> fix(test): add more randomness to issue variant name

- Makefile
- docker-compose.yaml
- ui/Dockerfile
Add Juno UI build and run stage to docker compose.
> Add UI image build and run

- Makefile
- internal/entity/common.go
> Fix ui-down and entity/common 'unknown' string

- internal/database/mariadb/migrations/20250814152811_add_mv_count_issue_ratings_refresh_event.up.sql
> Fix problems with NULL primary keys in mv tables

- internal/database/mariadb/database.go
> Increase db memory

- internal/database/mariadb/database.go
This reverts commit e4d73266ad35afdb0e55ac396a2ffee526b3cf55.
> Revert "feat: increase db memory (#861)"

- Makefile
- go.mod
- internal/database/mariadb/database.go
- internal/database/mariadb/migrations/20250808130224_add_mv_service_issue_counts_refresh_event.up.sql
- internal/database/mariadb/migrations/20250814152811_add_mv_count_issue_ratings_refresh_event.up.sql
- internal/database/mariadb/migrations/20250827115156_add_mv_count_vulnerability_component.up.sql
- internal/database/mariadb/migrations/20250908212342_post_migration_procedures.down.sql
- internal/database/mariadb/migrations/20250908212342_post_migration_procedures.up.sql
- internal/database/mariadb/test/database_manager.go
- internal/server/server.go
- scanner/k8s-assets/client/generated.go
- Add post migration procedures called just after migrations
- Add interface for adding/removing post migration procedures in sql schema
- Modify existing migrations removing mv calls
- Append removed mv calls to registry of post migration procedures
- Extract method for migration in service.go
- Add support for smart commit allowing changes in migration files
!changeexistingmigration
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
> Add post migration procedures and fix mv calls

- go.mod
- internal/database/mariadb/database.go
- internal/database/mariadb/migration.go
- internal/database/mariadb/test/database_manager.go
- implement parallel background execution of post migration procedures
- implement background job to keep connection opened
- add wait function to avoid background jobs in testing
- move migration functions from database.go to migration.go
> All post migrations run in background

- internal/database/mariadb/database.go
- internal/database/mariadb/migration.go
- internal/e2e/db_migration_test.go
- Refactor of db_migration_test
- Refactor USE clause in database.go
> Refactor db_migration_test and database.go
